"""
Run Agentic RAG Proof of Concept Demonstration.
Generates structured execution logs and summary for both Wealth Management clients.
"""

import json
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from src.agent.agentic_rag import wealth_agent

console = Console()


def run_demo():
    console.print(Panel.fit("[bold blue]Databricks Agentic RAG Proof of Concept[/bold blue]\n[green]FIBO Wealth Management & Unity Catalog Tool Registry[/green]"))

    client_ids = ["HNW-CLIENT-001", "HNW-CLIENT-002"]
    all_runs = []

    for cid in client_ids:
        console.print(f"\n[bold yellow]>>> Executing Multi-Hop Agentic Review for {cid}...[/bold yellow]")
        result = wealth_agent.execute_advisory_review(client_id=cid)
        all_runs.append(result)

        report = result["report"]
        traces = result["execution_traces"]

        # Traces Table
        trace_table = Table(title=f"Reasoning Traces: {report['client_name']}")
        trace_table.add_column("Step", style="cyan", width=6)
        trace_table.add_column("Type", style="magenta", width=14)
        trace_table.add_column("Action", style="green")
        trace_table.add_column("Details", style="white")

        for t in traces:
            trace_table.add_row(
                str(t["step"]),
                t["type"],
                t["action"],
                json.dumps(t["details"], ensure_ascii=False)[:80] + "...",
            )
        console.print(trace_table)

        # Portfolio Summary Table
        summary_table = Table(title=f"Portfolio Breakdown: {report['client_name']} ({report['risk_profile']['tolerance_level']})")
        summary_table.add_column("Portfolio", style="cyan")
        summary_table.add_column("AUM", style="green")
        summary_table.add_column("Holdings Count", style="yellow")
        summary_table.add_column("Suitability Status", style="bold red")

        for p, s in zip(report["portfolios"], report["suitability_evaluations"]):
            summary_table.add_row(
                p["portfolio_name"],
                f"${p['total_aum']:,.2f}",
                str(len(p["holdings"])),
                s["suitability_status"],
            )
        console.print(summary_table)

        console.print("\n[bold]Recommendations Generated by Agent:[/bold]")
        for rec in report["recommendation_summary"]:
            console.print(f"  • {rec}")

    # Save structured test logs
    output_path = "agent_execution_logs.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(all_runs, f, indent=2)
    console.print(f"\n[bold green]Structured test logs written to {output_path}[/bold green]")


if __name__ == "__main__":
    run_demo()

